import { createApp } from 'vue'
import App from './App.vue'
import './styles/fonts.css'
import './styles/tokens.css'
import './styles.css'
import './styles/layout.css'
import './styles/auth.css'
import './styles/employees.css'
import './styles/unified-theme.css'
import './styles/unified-content.css'
import './styles/unified-auth.css'
import './styles/aurora-shell.css'
import './styles/dashboard-density.css'
import './styles/business.css'
import './styles/product-images.css'
import './styles/readability.css'
import './styles/simple-theme.css'
import './styles/proposal-layout.css'
import './styles/profile.css'
import './styles/convergence.css'

createApp(App).mount('#app')
