<script setup>
import { computed, onMounted, ref } from 'vue'
import { api } from '../services/api'
const items=ref([]),loading=ref(true),error=ref(''),query=ref(''),risk=ref(''),action=ref('')
const actions=computed(()=>[...new Set(items.value.map(x=>x.action))]);const filtered=computed(()=>items.value.filter(x=>(!query.value||`${x.operatorName} ${x.summary} ${x.objectType} ${x.objectId}`.toLowerCase().includes(query.value.toLowerCase()))&&(!risk.value||x.riskLevel===risk.value)&&(!action.value||x.action===action.value)))
async function load(){loading.value=true;error.value='';try{items.value=(await api.auditLogs()).items}catch(e){error.value=e.message}finally{loading.value=false}}
onMounted(load)
</script>
<template><section class="business-page"><div class="page-heading"><div><h2>操作日志</h2><p>合并展示管理后台与微信小程序的重要真实操作，前端不可删除</p></div><span class="audit-lock"><span class="material-symbols-outlined">lock</span>审计保护已开启</span></div><div v-if="error" class="inline-error">{{error}}<button @click="load">重试</button></div>
  <article class="data-card"><div class="filterbar"><div class="filters"><label><span class="material-symbols-outlined">search</span><input v-model="query" placeholder="搜索操作人/对象/内容" /></label><select v-model="action"><option value="">全部动作</option><option v-for="x in actions" :key="x">{{x}}</option></select><select v-model="risk"><option value="">全部风险</option><option value="normal">普通</option><option value="warning">警告</option><option value="danger">高风险</option></select></div><span class="muted">{{filtered.length}} 条日志</span></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>时间</th><th>操作人</th><th>动作</th><th>对象</th><th>变更摘要</th><th>原因</th><th>来源</th><th>风险</th></tr></thead><tbody><tr v-for="log in filtered" :key="`${log.source}-${log.id}`"><td class="mono muted">{{log.createdAt}}</td><td><b>{{log.operatorName||'—'}}</b><small>{{log.operatorRole||'—'}}</small></td><td>{{log.action}}</td><td><span class="mono">{{log.objectType}} #{{log.objectId}}</span></td><td>{{log.summary||'—'}}</td><td>{{log.reason||'—'}}</td><td>{{log.source}}</td><td><span class="status-pill" :class="log.riskLevel">{{({normal:'普通',warning:'警告',danger:'高风险'})[log.riskLevel]}}</span></td></tr><tr v-if="!filtered.length&&!loading"><td colspan="8" class="empty-result">暂无符合条件的操作日志</td></tr></tbody></table></div></article><div v-if="loading" class="loading-line"></div></section></template>
