<script setup>
import { computed, onMounted, ref } from 'vue'
import { api } from '../services/api'
import { money } from '../utils/format'
import { canAccess } from '../utils/access'
import { downloadCSV } from '../utils/csv'

const props = defineProps({ currentUser: Object })
const emit = defineEmits(['toast'])
const loading=ref(true),saving=ref(false),error=ref(''),products=ref([]),canViewCost=ref(false),query=ref(''),businessType=ref(''),stockStatus=ref(''),editing=ref(null)
const imageInput=ref(null),selectedImage=ref(null),imagePreview=ref('')
const blank=()=>({name:'',code:'',businessType:'服装',category:'',specCount:1,costPrice:0,lowStockThreshold:5,location:'',price:0,status:'销售中',image:''})
const payload=p=>Object.fromEntries(Object.keys(blank()).filter(key=>key!=='code').map(key=>[key,p[key]]))
const form=ref(blank())
const canEdit=computed(()=>canAccess(props.currentUser,'products.edit'))
const canExport=computed(()=>canAccess(props.currentUser,'products.export'))
const filteredProducts=computed(()=>products.value.filter(p=>{const k=query.value.trim().toLowerCase();return(!k||`${p.name} ${p.code}`.toLowerCase().includes(k))&&(!businessType.value||p.businessType===businessType.value)&&(!stockStatus.value||(stockStatus.value==='有货'?p.stock>0:p.stock===0))}))
const metrics=computed(()=>({active:products.value.filter(p=>p.status==='销售中').length,clothing:products.value.filter(p=>p.businessType==='服装').length,cosmetics:products.value.filter(p=>p.businessType==='化妆品').length,incomplete:products.value.filter(p=>!p.image||!p.category).length}))
async function load(){loading.value=true;error.value='';try{const data=await api.products();products.value=data.items;canViewCost.value=data.canViewCost}catch(e){error.value=e.message}finally{loading.value=false}}
function revokePreview(){if(imagePreview.value.startsWith('blob:'))URL.revokeObjectURL(imagePreview.value)}
function resetImage(image=''){revokePreview();selectedImage.value=null;imagePreview.value=image;if(imageInput.value)imageInput.value.value=''}
function openCreate(){editing.value={id:null};form.value=blank();resetImage()}
function openEdit(p){editing.value=p;form.value={...blank(),...p};resetImage(p.image||'')}
function close(){if(!saving.value){editing.value=null;resetImage()}}
function chooseProductImage(event){const [file]=event.target.files||[];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){error.value='请选择 JPG、PNG 或 WebP 图片';emit('toast',error.value);event.target.value='';return}if(file.size>5*1024*1024){error.value='商品图片不能超过 5 MB';emit('toast',error.value);event.target.value='';return}revokePreview();selectedImage.value=file;imagePreview.value=URL.createObjectURL(file);error.value=''}
function removeProductImage(){resetImage();form.value.image=''}
async function save(){saving.value=true;error.value='';try{if(selectedImage.value){const uploaded=await api.uploadProductImage(selectedImage.value);form.value.image=uploaded.url}const result=editing.value.id?await api.updateProduct(editing.value.id,payload(form.value)):await api.createProduct(payload(form.value));const item=result.item;const i=products.value.findIndex(p=>p.id===item.id);i<0?products.value.unshift(item):products.value.splice(i,1,item);emit('toast',editing.value.id?'商品已更新':`商品已创建，编号 ${item.code}`);editing.value=null;resetImage()}catch(e){error.value=e.message;emit('toast',error.value)}finally{saving.value=false}}
async function toggleStatus(p){try{await api.updateProduct(p.id,payload({...p,status:p.status==='销售中'?'已停用':'销售中'}));emit('toast',p.status==='销售中'?'商品已停用':'商品已启用');await load()}catch(e){error.value=e.message}}
function exportCSV(){downloadCSV('商品列表.csv',[['商品名称','编号','业务类型','分类','库存','成本价','售价','状态'],...filteredProducts.value.map(p=>[p.name,p.code,p.businessType,p.category,p.stock,canViewCost.value?p.costPrice:'无权限',p.price,p.status])]);emit('toast','商品列表已导出')}
onMounted(load)
</script>

<template>
  <section class="products-page">
    <div class="page-heading"><div><h2>商品中心</h2><p>集中维护商品资料、价格和销售状态；规格库存由小程序经营流程维护</p></div><div class="heading-actions"><button v-if="canExport" class="secondary" @click="exportCSV"><span class="material-symbols-outlined">download</span>导出</button><button v-if="canEdit" class="primary" @click="openCreate"><span class="material-symbols-outlined">add</span>新建商品</button></div></div>
    <div class="metrics product-metrics"><article><div><span>在售</span><strong>{{metrics.active}}</strong></div><i class="blue"><span class="material-symbols-outlined">storefront</span></i></article><article><div><span>服装</span><strong>{{metrics.clothing}}</strong></div><i class="cyan"><span class="material-symbols-outlined">styler</span></i></article><article><div><span>化妆品</span><strong>{{metrics.cosmetics}}</strong></div><i class="pink"><span class="material-symbols-outlined">face_retouching_natural</span></i></article><article class="alert"><div><span>资料待完善</span><strong>{{metrics.incomplete}}</strong></div><i><span class="material-symbols-outlined">warning</span></i></article></div>
    <article class="products-card"><div class="filterbar"><div class="filters"><label><span class="material-symbols-outlined">search</span><input v-model="query" placeholder="搜索名称/编号" /></label><select v-model="businessType"><option value="">全部业务</option><option>服装</option><option>化妆品</option></select><select v-model="stockStatus"><option value="">全部库存</option><option>有货</option><option>缺货</option></select></div><span class="muted">共 {{filteredProducts.length}} 条</span></div>
      <div v-if="error" class="inline-error"><span class="material-symbols-outlined">error</span>{{error}}<button @click="load">重新加载</button></div>
      <div class="products-table-wrap"><table class="products-table"><thead><tr><th>商品</th><th>编号</th><th>业务类型</th><th>分类</th><th class="right">规格</th><th class="right">库存</th><th class="right">成本价</th><th class="right">参考售价</th><th>状态</th><th v-if="canEdit" class="center">操作</th></tr></thead><tbody><tr v-for="p in filteredProducts" :key="p.id"><td><div class="product-cell"><img v-if="p.image" :src="p.image" alt=""><span v-else class="product-placeholder"><span class="material-symbols-outlined">inventory_2</span></span><b>{{p.name}}</b></div></td><td class="mono muted">{{p.code}}</td><td>{{p.businessType}}</td><td>{{p.category}}</td><td class="right mono">{{p.specCount}}</td><td class="right mono" :class="{error:p.stock===0}">{{p.stock}}</td><td class="right mono">{{canViewCost?money(p.costPrice):'无权限'}}</td><td class="right mono">{{money(p.price)}}</td><td><span class="product-status" :class="{empty:p.status!=='销售中'}"><i></i>{{p.status}}</span></td><td v-if="canEdit" class="center"><div class="row-actions always"><button @click="openEdit(p)">编辑</button><button @click="toggleStatus(p)">{{p.status==='销售中'?'停用':'启用'}}</button></div></td></tr><tr v-if="!filteredProducts.length&&!loading"><td :colspan="canEdit?10:9" class="empty-result">没有符合条件的商品</td></tr></tbody></table></div>
    </article><div v-if="loading" class="loading-line"></div>
    <div v-if="editing" class="dialog-backdrop" @mousedown.self="close"><form class="business-dialog wide" @submit.prevent="save"><div class="dialog-title"><div><h3>{{editing.id?'编辑商品':'新建商品'}}</h3><p>商品资料不会直接覆盖库存余额</p></div><button type="button" class="icon-button" @click="close"><span class="material-symbols-outlined">close</span></button></div><div class="form-grid"><label><span>商品名称 *</span><input v-model.trim="form.name" required /></label><label><span>商品编号</span><input :value="editing.id?form.code:'保存后自动生成'" disabled /></label><label><span>业务类型 *</span><select v-model="form.businessType"><option>服装</option><option>化妆品</option></select></label><label><span>分类 *</span><input v-model.trim="form.category" required /></label><label v-if="canViewCost"><span>成本价</span><input v-model.number="form.costPrice" type="number" min="0" step="0.01" /></label><label><span>参考售价</span><input v-model.number="form.price" type="number" min="0" step="0.01" /></label><label><span>规格数</span><input v-model.number="form.specCount" type="number" min="0" /></label><label><span>低库存阈值</span><input v-model.number="form.lowStockThreshold" type="number" min="0" /></label><label><span>货位</span><input v-model.trim="form.location" placeholder="例如 A-01" /></label><label><span>状态</span><select v-model="form.status"><option>销售中</option><option>已停用</option></select></label><section class="product-image-field span-2"><span>商品图片</span><div class="product-image-picker"><span class="product-image-preview"><img v-if="imagePreview" :src="imagePreview" alt="商品图片预览"><span v-else class="material-symbols-outlined">add_photo_alternate</span></span><div><p>从手机相册或电脑中选择，支持 JPG、PNG、WebP，最大 5 MB。</p><span class="product-image-actions"><button type="button" class="secondary compact" :disabled="saving" @click="imageInput.click()">{{imagePreview?'重新选择':'选择图片'}}</button><button v-if="imagePreview" type="button" class="text-button" :disabled="saving" @click="removeProductImage">移除图片</button></span></div><input ref="imageInput" class="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" @change="chooseProductImage"></div></section></div><div class="dialog-actions"><button type="button" class="secondary" @click="close">取消</button><button class="primary" :disabled="saving">{{saving?'保存中…':'保存商品'}}</button></div></form></div>
  </section>
</template>
